name: Merry360xMobile
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
targets:
  Merry360xMobile:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Merry360xMobile
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.merry360x.mobile
        PRODUCT_NAME: Merry360xMobile
        INFOPLIST_KEY_CFBundleDisplayName: Merry360x
        INFOPLIST_KEY_CFBundleURLTypes: >-
          [{"CFBundleURLName":"com.merry360x.mobile.oauth","CFBundleURLSchemes":["merry360x"]}]
        INFOPLIST_KEY_UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        "INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 9
        MARKETING_VERSION: 1.3.0
    scheme:
      testTargets: []
